//LOCALHOST Routes
###Gets all the contacts
GET http://localhost:3000/contacts

###Gets Juan contact
GET http://localhost:3000/contacts/626c14de5c2228737d83ae27

###Post a contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Pedro",
    "lastName": "Borgonoz",
    "email":"pedrojose@gmail.com",
    "favoritecolor":"Purple",
    "birthday":"01/10/2005"
}

###Update a contact
PUT http://localhost:3000/contacts/626c2a5e5c2228737d83ae29 HTTP/1.1
content-type: application/json

{
    "firstName" :"Isaac",
    "lastName":"Naranjo",
    "email":"i.naranjo@gmail.com",
    "favoriteColor":"Black",
    "birthday":"06/06/2006"
}

### DELETE contact Juan Naranjo
DELETE http://localhost:3000/contacts/626c14de5c2228737d83ae27 HTTP/1.1

//Heroku Routes

###GET all contacts
GET https://cse341-api.herokuapp.com/contacts

### GET Marisol
GET https://cse341-api.herokuapp.com/contacts/626c149b5c2228737d83ae24

###Post a contact
POST https://cse341-api.herokuapp.com/contacts
content-type: application/json

{
    "firstName":"Pedro",
    "lastName": "Borgonoz",
    "email":"p.jose@gmail.com",
    "favoriteColor":"Purple",
    "birthday":"01/10/2005"
}

###Update a contact
PUT https://cse341-api.herokuapp.com/contacts/6274580db4cc0adb0b9bf713
content-type: application/json

{
    "firstName" :"Pedro",
    "lastName":"Borgonoz",
    "email":"pedrojose@gmail.com",
    "favoriteColor":"Black",
    "birthday":"06/06/2006"
}

### DELETE contact Juan Naranjo
DELETE https://cse341-api.herokuapp.com/contacts/62745822b4cc0adb0b9bf714