
GET http://localhost:3000/contacts

###

GET https://cse341-api.herokuapp.com/contacts

###

GET http://localhost:3000/contacts/626c149b5c2228737d83ae24

###

GET https://cse341-api.herokuapp.com/contacts/626c149b5c2228737d83ae24